import mods.jei.JEI;
import mods.zenutils.I18n;
import mods.zenutils.DataUpdateOperation.APPEND;
import mods.nuclearcraft.AlloyFurnace;
import mods.modularmachinery.MachineModifier;
import crafttweaker.item.IItemStack;
<modularmachinery:giga_blackholecore_controller>.addTooltip("这个模块化几乎没有任何用处，仅作为对模块化的装饰。");
<modularmachinery:giga_blackholecore_controller>.addTooltip("您也可以使用此模块化对基地进行装饰。");
<modularmachinery:giga_blackholecore_controller>.addTooltip("模型来源于:新型工程:奇点核心-Hikari_Nova");
<modularmachinery:giga_blackholecore_controller>.addTooltip("§4模型已获得原作者授权，未经授权严禁二次分发§f");
<modularmachinery:giga_singularitycore_controller>.addTooltip("这个模块化几乎没有任何用处，仅作为对模块化的装饰。");
<modularmachinery:giga_singularitycore_controller>.addTooltip("您也可以使用此模块化对基地进行装饰。");
<modularmachinery:giga_singularitycore_controller>.addTooltip("模型来源于:新型工程:奇点核心-Hikari_Nova");
<modularmachinery:giga_singularitycore_controller>.addTooltip("§4模型已获得原作者授权，未经授权严禁二次分发§f");

val ITEMINFO as string = "§e//////// 物品信息 / 等级 / 功能 ////////";

static DIFF as string[int] = {
    1:"§9难度: §a§l§n1§a.",
    2:"§9难度: §a§l§n2§a.",
    3:"§9难度: §a§l§n3§a.",
    4:"§9难度: §b§l§n4§b.",
    5:"§9难度: §b§l§n5§b.",
    6:"§9难度: §5§l§n6§5.",
    7:"§9难度: §5§l§n7§5.",
    8:"§9难度: §5§l§n8§5.",
    9:"§9难度: §6§l§n9§6.",
    10:"§9难度: §6§l§n10§6.",
    11:"§9难度: §c§l§n11§c.",
    12:"§9难度: §c§l§n12§c.",
    13:"§9难度: §4§l§n13§c.",
    14:"§9难度: §4§l§n14§c.",
};



function addMachineinformation_fact(name as string,level as int,diff as int,removenormal as bool){
    val example as IItemStack = <item:modularmachinery:${name}_factory_controller>;
    val normal_controller as IItemStack = <item:modularmachinery:${name}_controller>;
    if(removenormal)JEI.removeAndHide(normal_controller);
    example.addTooltip("§e//////// 机械信息 / 等级 / 功能 ////////");
     if(level < 15){
        example.addTooltip(DIFF[level] + diff);
        MachineModifier.setMachinePrefix(name, DIFF[level] + diff);
    }else{
        if(level == 15)example.addTooltip("#875CFF-42FFD0-8E42FF难度:ASTEROID_CLIMAX§b(§9§l15.0§r§b)");
        if(level == 16)example.addTooltip("#0B4F60-FF2600-A84938难度:PLANET_LIMIT§c(§4§l16.0§r§c)");
        if(level == 17)example.addTooltip("#002080-8AD8FF-3754A9难度:DIMENSION_SUMMIT§9(§1§l17.0§r§9)");
        if(level == 18)example.addTooltip("#5D0070-A78D2F-005875难度:REINCARNATE_CULMINATION§5(§e§l18.0§r§5)");
        if(level == 19)example.addTooltip("#050505-4D4D4D-FFFFFF难度:NEGATIVE_PRIME§0(§8§l19.0§r§0)");
    }
    var tooltipRegister = 1;
    while (I18n.hasKey("EndTech." + name + ".tooltip" + tooltipRegister)){
        example.addTooltip(I18n.format("EndTech." + name + ".tooltip" + tooltipRegister));
        tooltipRegister += 1;
    }
    example.addTooltip("§9//////// 控制器提示 ////////");
    example.addTooltip("§9§o控制器的工厂变种,包含特殊功能");
    example.addTooltip("§9§oJEI 中左键以查看结构");
    example.addTooltip("§9§o放置后右键查看机械运行状态");
    <ore:EndTech>.add(example);
    var EndeTechFlag = mods.rainbowtooltip.RainbowTooltip.formatWithSpeed("由[EndTech]添加", 2000);
    example.addTooltip(EndeTechFlag);
}

function addMachineinformation_normal(name as string,level as int,diff as int){
    val example as IItemStack = <item:modularmachinery:${name}_controller>;
    example.addTooltip("§e//////// 机械信息 / 等级 / 功能 ////////");
     if(level < 15){
        example.addTooltip(DIFF[level] + diff);
        MachineModifier.setMachinePrefix(name, DIFF[level] + diff);
    }else{
        if(level == 15)example.addTooltip("#875CFF-42FFD0-8E42FF难度:ASTEROID_CLIMAX§b(§9§l15.0§r§b)");
        if(level == 16)example.addTooltip("#0B4F60-FF2600-A84938难度:PLANET_LIMIT§c(§4§l16.0§r§c)");
        if(level == 17)example.addTooltip("#002080-8AD8FF-3754A9难度:DIMENSION_SUMMIT§9(§1§l17.0§r§9)");
        if(level == 18)example.addTooltip("#5D0070-A78D2F-005875难度:REINCARNATE_CULMINATION§5(§e§l18.0§r§5)");
        if(level == 19)example.addTooltip("#050505-4D4D4D-FFFFFF难度:NEGATIVE_PRIME§0(§8§l19.0§r§0)");
    }
    var tooltipRegister = 1;
    while (I18n.hasKey("EndTech." + name + ".tooltip" + tooltipRegister)){
        example.addTooltip(I18n.format("EndTech." + name + ".tooltip" + tooltipRegister));
        tooltipRegister += 1;
    }
    example.addTooltip("§9//////// 控制器提示 ////////");
    example.addTooltip("§9§o每个机械的独立控制器,JEI 中左键以查看结构");
    example.addTooltip("§9§oJEI 中左键以查看结构");
    example.addTooltip("§9§o放置后右键查看机械运行状态");
    <ore:EndTech>.add(example);
    var EndeTechFlag = mods.rainbowtooltip.RainbowTooltip.formatWithSpeed("由[EndTech]添加", 2000);
    example.addTooltip(EndeTechFlag);
}
function addIteminformation(name as string,level as int,diff as int){
    val example as IItemStack = <item:contenttweaker:${name}>;
    example.addTooltip("§e//////// 物品信息 / 等级 / 功能 ////////");
    if(level < 15){
        example.addTooltip(DIFF[level] + diff);
    }else{
        if(level == 15)example.addTooltip("#875CFF-42FFD0-8E42FF难度:ASTEROID_CLIMAX§b(§9§l15.0§r§b)");
        if(level == 16)example.addTooltip("#0B4F60-FF2600-A84938难度:PLANET_LIMIT§c(§4§l16.0§r§c)");
        if(level == 17)example.addTooltip("#002080-8AD8FF-3754A9难度:DIMENSION_SUMMIT§9(§1§l17.0§r§9)");
        if(level == 18)example.addTooltip("#5D0070-A78D2F-005875难度:REINCARNATE_CULMINATION§5(§e§l18.0§r§5)");
        if(level == 19)example.addTooltip("#050505-4D4D4D-FFFFFF难度:NEGATIVE_PRIME§0(§8§l19.0§r§0)");
        if(level == 999)example.addTooltip("#0044B3-0D4EB7-1958BB-2663C0-336DC4-4077C8-4C81CC-598BD1-6695D5-73A0D9-7FAADD-8CB4E1-99BEE6-A5C8EA-B2D2EE-BFDDF2-CCE7F7-D8F1FB-E5FBFF难度:PER ASPERA AD ASTRA§9(§b§lAIN§9§l)");
        if(level == 998)example.addTooltip("#ff0010-e30095-cc00ff难度:ENDLESS X LIMITLESS§9(§b§lOCT§9§l)");
        if(level == 114)example.addTooltip("#0044B3-0D4EB7-1958BB-2663C0-336DC4-4077C8-4C81CC-598BD1-6695D5-73A0D9-7FAADD-8CB4E1-99BEE6-A5C8EA-B2D2EE-BFDDF2-CCE7F7-D8F1FB-E5FBFF难度:PLAYER_YUNYOUAIR§9(§b§l114§9§l)");
        if(level == 514)example.addTooltip("#0044B3-0D4EB7-1958BB-2663C0-336DC4-4077C8-4C81CC-598BD1-6695D5-73A0D9-7FAADD-8CB4E1-99BEE6-A5C8EA-B2D2EE-BFDDF2-CCE7F7-D8F1FB-E5FBFF难度:PLAYER_BAITANG233§9(§b§l514§9§l)");
        if(level == 123)example.addTooltip("§9难度:§f#FFFFFFIRID#00008bIOSAM#FFFFE0ARIUM§9(§b§l123§9§l)");
    }
    var tooltipRegister = 1;
    while (I18n.hasKey("EndTech." + name + ".tooltip" + tooltipRegister)){
        example.addTooltip(I18n.format("EndTech." + name + ".tooltip" + tooltipRegister));
        tooltipRegister += 1;
    }
    <ore:EndTechItems>.add(example);
    var EndeTechFlag = mods.rainbowtooltip.RainbowTooltip.formatWithSpeed("由[EndTech]添加", 2000);
    example.addTooltip(EndeTechFlag);
}
<contenttweaker:unknownplanet>.addTooltip("§e一组通过天体射电波获取的数据集");
<contenttweaker:unknownplanet>.addTooltip("§a需要在§e天体观测分析中心§e进行进一步的探测来获取其成分");
addIteminformation("unknownplanet",8,0);
<contenttweaker:orichalcosplanet>.addTooltip("§d这颗行星散发着神话一般的光芒");
<contenttweaker:orichalcosplanet>.addTooltip("§e存储着行星的坐标数据");
addIteminformation("orichalcosplanet",10,0);
<contenttweaker:shingplanet>.addTooltip("§f这颗行星闪烁着明洁的光辉");
<contenttweaker:shingplanet>.addTooltip("§e存储着行星的坐标数据");
addIteminformation("shingplanet",10,0);
<contenttweaker:infinityplanet>.addTooltip("§b这颗行星在宇宙中永恒地律动着");
<contenttweaker:infinityplanet>.addTooltip("§e存储着行星的坐标数据");
addIteminformation("infinityplanet",12,0);
addIteminformation("casmir_effect_seq",11,1);
addIteminformation("micro_mmf_accelerator",11,1);
addIteminformation("spacetimeframework",10,5);
addIteminformation("shieldcase",7,1);
addIteminformation("reflectcore",10,3);
addIteminformation("darkmatters",12,1);
addIteminformation("degenerationmatter",10,5);
addIteminformation("skydust",10,1);
addIteminformation("voidmatter",14,1);
addIteminformation("fieldofgravitycore",10,1);
addIteminformation("normalplanet",10,1);
addIteminformation("enderplanet",10,1);
addIteminformation("hellplanet",10,1);
addIteminformation("nanoplanet",10,5);
addIteminformation("depressplanet",10,5);
addIteminformation("magnetplanet",10,5);
addIteminformation("oredrone1",9,5);
addIteminformation("mk1satellite",9,5);
addIteminformation("mk1observer",9,5);
addIteminformation("mk1rocket",9,5);
addIteminformation("lockednormalplanet",11,8);
addIteminformation("lockedhellplanet",11,8);
addIteminformation("lockedenderplanet",11,8);
addIteminformation("tearenginee",11,3);
addIteminformation("forcemanucontainer",10,8);
addIteminformation("forcecontainer",11,1);
addIteminformation("spacematrix_ingot",10,8);
addIteminformation("superconidiosome",11,3);
addIteminformation("nanoglassmetal",11,3);
addIteminformation("dust",11,1);
addIteminformation("opticsunit",10,8);
addIteminformation("constructunit",9,1);
addIteminformation("nanoswarm",11,8);
addIteminformation("cfcm",10,8);
addIteminformation("thor_blueprint",11,3);
addIteminformation("harc_blueprint",10,1);
addIteminformation("perihelion_blueprint",15,1);
addIteminformation("zero_pressure_blueprint",11,7);
addIteminformation("similardarkmatter",12,8);
addIteminformation("mk2satellite",10,8);
addIteminformation("mk2oredrone",10,8);
addIteminformation("mk2observer",10,8);
addIteminformation("mk2rocket",10,8);
addIteminformation("octingot",12,8);
addIteminformation("inactivenanites",10,8);
addIteminformation("nanites",11,1);
addIteminformation("thorupgrade1",10,1);
addIteminformation("wisecore",11,1);
addIteminformation("gama_tialcoil",8,0);
addIteminformation("gama_tialalloy",8,0);
addIteminformation("beccomputer",12,1);
addIteminformation("becmemory",12,1);
addIteminformation("recoilengine",13,3);
addIteminformation("scan_terminal_spacestation",1,0);
addIteminformation("scan_terminal_elevator",1,0);
addIteminformation("atomicclock",12,3);
addIteminformation("ultminingdevice",12,5);
addIteminformation("spacetime_lens",11,8);
addIteminformation("lightplatform",10,3);
addIteminformation("assemblycore",10,8);
addIteminformation("axis_blueprint",17,0);
addIteminformation("neutron_similar_blueprint",13,9);
addIteminformation("spacestation_i_blueprint",8,7);
addIteminformation("spacestation_ii_blueprint",11,0);
addIteminformation("collapse_blueprint",11,2);
addIteminformation("dimensioncarver_blueprint",16,0);
addIteminformation("se_blueprint",16,0);
addIteminformation("se_core",16,0);
addIteminformation("central_saved",10,0);
addIteminformation("nova_ingot",14,1);
addIteminformation("mineral",14,1);
addIteminformation("exoticgases",14,1);
addIteminformation("shroud_needle",16,1);
addIteminformation("shroudplanet",16,1);
addIteminformation("shroudchunk",17,1);
addIteminformation("cosmic_data",18,1);
addIteminformation("hyperdimensional_computer",18,1);
addIteminformation("phantom_calculation_array",17,1);
addIteminformation("arcance_ingot",17,1);
addIteminformation("timespace_ingot",18,1);
addIteminformation("hyperdimensional_lens",18,1);
addIteminformation("arcance_lens",17,1);
addIteminformation("hyperdimensional_blueprint",18,1);
addIteminformation("overreachedspace_blueprint",17,1);
addIteminformation("negativephase_matter",19,1);
addIteminformation("alloy",15,1);
addIteminformation("entropy_singularity",19,1);
addIteminformation("sn_blueprint",17,1);
addIteminformation("aal_blueprint",17,1);
addIteminformation("dfea_blueprint",17,1);
addIteminformation("psm_blueprint",17,1);
addIteminformation("timespacesingularity_blueprint",18,1);
addIteminformation("cosmiccasket_blueprint",18,1);
addIteminformation("sn_core",17,1);
addIteminformation("aal_core",17,1);
addIteminformation("dfea_core",17,1);
addIteminformation("psm_core",17,1);
addIteminformation("timespacesingularity_core",18,1);
addIteminformation("cosmiccasket_core",18,1);
addIteminformation("neutrondustingot",11,3);
addIteminformation("planetoflight",11,8);
addIteminformation("dustupgrade",13,1);
addIteminformation("novamatrix",15,1);
addIteminformation("timespace_coil_block",18,1);
addIteminformation("gama_tial_coil_block",13,1);
addIteminformation("eternity_coil_block",19,1);
addIteminformation("arcancemachineblock",17,1);
addIteminformation("arcancemartrix",19,1);
addIteminformation("starmachineblock",10,1);
addIteminformation("asteroidcontrolblock",11,1);
addIteminformation("superglassbluex",8,5);
addIteminformation("superglassred",8,5);
addIteminformation("superglassyellow",8,5);
addIteminformation("superglassgreen",8,5);
addIteminformation("superglasscyan",8,5);
addIteminformation("superglasspurple",8,5);
addIteminformation("superglasswhite",8,5);
addIteminformation("superglassorange",8,5);
addIteminformation("darkmatterblock",12,8);
addIteminformation("space_engblock",8,5);
addIteminformation("dimensiontwistblock",11,5);
addIteminformation("basicglass",14,1);
addIteminformation("planetstructure",10,5);
addIteminformation("superspacestructure",16,1);
addIteminformation("heatmatrix",10,8);
addIteminformation("dustmatrix",13,8);
addIteminformation("stablestructure",10,8);
addIteminformation("superspace_star_controlmatrix",11,8);
addIteminformation("starvoidstructure",13,1);
addIteminformation("caldevice",11,3);
addIteminformation("milkmachineblock",12,8);
addIteminformation("respacetimeblock",16,1);
addIteminformation("energycube_mk1",7,5);
addIteminformation("energycube_mk2",9,5);
addIteminformation("energycube_mk3",11,5);
addIteminformation("atomcoolingblock",11,8);
addIteminformation("superinstanceblock",11,8);
addIteminformation("supermanablock",11,8);
addIteminformation("dimensioncarver_energyfocusunit",15,1);
addIteminformation("dimensioncarver_reinforcedblock",15,1);
addIteminformation("dimensioncarver_energyfield",15,1);
addIteminformation("spacexmachineblock",15,1);
addIteminformation("spacexlightingblock",16,1);
addIteminformation("neutronismblock",10,3);
addIteminformation("comhostmk1",8,5);
addIteminformation("comhostmk2",11,5);
addIteminformation("comhostmk3",14,5);
addIteminformation("arkswarm",15,0);
addIteminformation("dustswarm",16,0);
addIteminformation("universalswarm",17,0);
addIteminformation("weakmag",16,0);
addIteminformation("strongmag",17,0);
addIteminformation("mripcb",16,0);
addIteminformation("magswarm",17,0);
addIteminformation("ctc_computer",16,0);
addIteminformation("smripcb",16,0);
addIteminformation("synthesischip",4,5);
addIteminformation("crystalchip",8,0);
addIteminformation("universalalloychip",9,5);
addIteminformation("neutronchip",11,5);
addIteminformation("infinitychip",13,5);
addIteminformation("arkchip",15,0);
addIteminformation("etherengine_upgrade",15,0);
addIteminformation("warmatrix_terminal",10,6);
addIteminformation("helioscomputer",10,0);
addIteminformation("heliosmemory",10,0);
addIteminformation("nuclear_well",8,0);
addIteminformation("space_elevator_power_module",16,0);
addIteminformation("space_elevator_structure",15,0);
addIteminformation("space_elevator_connector",15,0);
addIteminformation("infinity_frame",11,8);
addIteminformation("arcance_soc",17,0);
addIteminformation("hyperdimensional_soc",17,0);
addIteminformation("space_array",18,0);
addIteminformation("yuriisydoll",999,0);
addIteminformation("octoberdoll",998,0);
addIteminformation("zp_upgrade",15,0);
addIteminformation("charged_fuel_v1",9,2);
addIteminformation("charged_fuel_v2",10,3);
addIteminformation("charged_fuel_v3",11,4);
addIteminformation("charged_fuel_v4",12,5);
addIteminformation("charged_fuel_v5",13,1);
addIteminformation("hyperlightspeedplatform",15,0);
addIteminformation("arcane_spacetime_expansion_generator",17,0);
addIteminformation("lightspeed_overclock_array",16,0);
addIteminformation("rtg3521fumo",1024,0);
addIteminformation("yunyouairfumo",114,0);
addIteminformation("baitang233fumo",514,0);
addIteminformation("hyper_stablestructure",17,0);
addIteminformation("dimensionally_transcendent_casing",15,0);
addIteminformation("hyper_strenth_machine_block",16,0);
addIteminformation("orichalcos_frame",9,2);
addIteminformation("ark_frame",13,8);
addIteminformation("nqalloy_frame",15,0);
addIteminformation("arcance_frame",17,0);
addIteminformation("infinity_glass",10,0);
addIteminformation("quantumgroup_glass",16,0);
addIteminformation("nq_alloy",16,0);
addIteminformation("hyperspace_structure",16,0);
addIteminformation("newmaafumo",123,0);
addIteminformation("mcdycfumo",666,0);
addIteminformation("quantum_ingot",16,0);
addIteminformation("quantum_frame",16,0);
addIteminformation("dimensional_bridge_casing",16,0);
addIteminformation("manipulator",16,0);
addIteminformation("dimensionally_coil",16,0);
addIteminformation("reverseunit_1",15,0);
addIteminformation("reverseunit_2",15,0);
addIteminformation("reverseunit_3",15,0);
addIteminformation("reverseunit_4",15,0);
addIteminformation("reverseunit_5",15,0);
addIteminformation("omhd_blueprint",13,4);
addIteminformation("ceas_blueprint",14,5);
addIteminformation("mk1satellite_generator",1,0);
addIteminformation("mk2satellite_generator",2,3);
addIteminformation("mk3satellite_generator",3,4);
addIteminformation("mk4satellite_generator",6,0);
addIteminformation("mk5satellite_generator",7,8);
addIteminformation("mk6satellite_generator",9,6);
addIteminformation("mk7satellite_generator",10,9);
addIteminformation("mk8satellite_generator",12,4);
addIteminformation("tci",8,5);
<contenttweaker:newmaafumo>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:newmaafumo>.addTooltip("§b我觉得你应该出门走走...");

<contenttweaker:mcdycfumo>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:mcdycfumo>.addTooltip("§b你真得谢谢他...");

<contenttweaker:yunyouairfumo>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:yunyouairfumo>.addTooltip("§b“循此苦旅,终抵群星”");

<contenttweaker:baitang233fumo>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:baitang233fumo>.addTooltip("§b“循此苦旅,终抵群星”");

<contenttweaker:rtg3521fumo>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:rtg3521fumo>.addTooltip("§b我觉得你应该出门走走...");

<contenttweaker:yuriisydoll>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:yuriisydoll>.addTooltip("§b“循此苦旅,终抵群星”");

<contenttweaker:octoberdoll>.addTooltip("§9感谢游玩终末工程");
<contenttweaker:octoberdoll>.addTooltip("§b“循此苦旅,终抵群星”");
//超能系列
addIteminformation("planet_ff",15,0);
addIteminformation("overworld_block",15,0);
addIteminformation("neb_block",15,0);
addIteminformation("edb_block",15,0);
addIteminformation("moonb_block",15,0);
addIteminformation("meb_block",15,0);
addIteminformation("mab_block",15,0);
addIteminformation("veb_block",15,0);
addIteminformation("plb_block",15,0);
addIteminformation("ceb_block",15,0);
addIteminformation("mmb_block",15,0);
addIteminformation("hab_block",15,0);
addIteminformation("npb_block",15,0);
addIteminformation("anb_block",15,0);
addIteminformation("mhb_block",15,0);
addIteminformation("hob_block",15,0);
addIteminformation("seb_block",15,0);
addIteminformation("tfb_block",15,0);
addIteminformation("ddb_block",15,0);
addIteminformation("ssps_terminal",8,9);
addMachineinformation_fact("newengineerworkshop1",1,1,true);
addMachineinformation_normal("newengineerworkshop1",1,1);
addMachineinformation_fact("starmagn-pro",13,5,false);
addMachineinformation_fact("superelect",2,5,false);
addMachineinformation_fact("surmount-ae",13,1,false);
addMachineinformation_fact("surmount-meteor",15,0,false);
addMachineinformation_fact("surmount-uts",15,0,false);
addMachineinformation_fact("wallcreation",15,5,false);
addMachineinformation_fact("particle_accelerator",10,6,false);

addMachineinformation_fact("aerospacefactory",8,5,false);
<modularmachinery:aerospacefactory_factory_controller>.addTooltip("§b以钢铁触碰深空");
<modularmachinery:aerospacefactory_factory_controller>.addTooltip("§7集成关键的§a高级火箭合成配方");
<modularmachinery:aerospacefactory_factory_controller>.addTooltip("§7制造各类§9航天器§7用以科技发展");
<modularmachinery:aerospacefactory_factory_controller>.addTooltip("§7制造多方块机器控制器的§9原型蓝图");
addMachineinformation_fact("asteroid_destroyer",11,5,false);
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§c一台真正的§4深空巨兽");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7接收普通,§c热域§7,§d末地§7三种基础行星来拟合解构集群");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7每颗行星可提供§a10000§7点可开采点数");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7每完成一次开采,§7将减少§c待开采集群§7的§91点§7可用点数");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7每采集完§a100§7点数时,§7将提升§c1§7级§7解构等级");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7每§c200§7级§7解构等级将增加§ax2倍§7基础产出");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7等级上限为§412000§7级,拥有§914§7个智能解构线程");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§7拥有两个插件槽");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§71:§e行星解构机-§e闪耀§f组件升级:§7提升§a2000§7级解构等级,且开放§c虹§e彩§9行§a星§7,§e闪耀行星§7,§d山铜行星§7的解构线程");
<modularmachinery:asteroid_destroyer_factory_controller>.addTooltip("§72:§c行星解构机-§4余烬§c组件升级:§7提升§a2000§7级解构等级,增加§c熔炼模式§7,可自由选择产出粗矿或产出矿锭");
addMachineinformation_fact("spacestation_i",8,7,false);
addMachineinformation_fact("asteroid_reactor",10,9,false);
<modularmachinery:asteroid_reactor_factory_controller>.addTooltip("§c我们需要更深入一些");
<modularmachinery:asteroid_reactor_factory_controller>.addTooltip("§7锁定§c热域行星§7,使用化学燃料推进至行星深层,吸收大量的§4天然重核聚变能");
<modularmachinery:asteroid_reactor_factory_controller>.addTooltip("§7当钻探深度大于§b1000KM§7时,提供§a100G/tick§7的发电,并产出等离子体和部分行星物质");
<modularmachinery:asteroid_reactor_factory_controller>.addTooltip("§7此后每深入§b1000KM§7将加倍发电量和物质产出,§7最大钻探深度为§66000KM");
<modularmachinery:asteroid_reactor_factory_controller>.addTooltip("§7钻探后§c行星稳定度§7将会根据深度§4持续降低§7,当到达§40.0§7时将解除锁定并产出§4余烬物质");
<modularmachinery:asteroid_reactor_factory_controller>.addTooltip("§7在不同的§4极端环境§7中,可以合成一些§9性质特殊§7的稀有材料");
addMachineinformation_fact("asteroidlockdevice",10,8,false);
addMachineinformation_fact("atomicprocessequipx",10,5,false);
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§b叩响新时代的大门");
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§7集成§e工业机械臂§7,§b装配线§7,§5集成式处理车间§7的所有配方并减少§690%§7的配方时间");
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§7存在大量独占配方");
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§9时空升级§7通过装载§3类空间§b透镜§7,§b星载原子钟§7,恒星级§1超§9时§b空§e核心反应矩阵");
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§7将在其原有基础上再次减少§699%§7运行时间");
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§7拥有§615§7个独立线程,每个线程拥有§a4096§7并行");
<modularmachinery:atomicprocessequipx_factory_controller>.addTooltip("§1终末已向您送去了邀请");
addMachineinformation_fact("communication_center",9,6,false);
<modularmachinery:communication_center_factory_controller>.addTooltip("§9寰宇星空,尽在我手");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7深空网络的§e核心机器");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7使用前需要先发射§9近地通信中枢§7来获取§a通信中枢§6量子上行链路§b同步器");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7当中枢异常掉线时可以使用§b同步器§7恢复与中枢的联系");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7当中枢§a正常运行§7时,它就可以与§6洛夫斯特罗姆基座§7建立连接");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7将绑定了§6基座控制器§7的§b模式定位坐标卡§7提供给中枢即可建立与基座的联系");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7中枢成型时的通信主机§a等级§7将决定§6基座§7可发射的航天器上限");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7通信主机§bMk1§7可提供的上限:§e200");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7通信主机§aMk2§7可提供的上限:§e1000");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7通信主机§9Mk3§7可提供的上限:§e2000");
<modularmachinery:communication_center_factory_controller>.addTooltip("§7注:所有通信主机必须使用§c同一型号§7,否则通信阵列将始终离线");
addMachineinformation_fact("coolingindustry",8,0,false);
<modularmachinery:coolingindustry_factory_controller>.addTooltip("§9到底有多冷!?");
<modularmachinery:coolingindustry_factory_controller>.addTooltip("§7快速制造§e超流氦§7,§b极寒之凛冰§7,§1熔融极寒末影§7,§3IC2冷却液");
addMachineinformation_fact("dustcollector",10,5,true);
<modularmachinery:dustcollector_factory_controller>.addTooltip("§8尘埃物质§9吸积盘§7的§6集成控制器版本");
<modularmachinery:dustcollector_factory_controller>.addTooltip("§7拥有§a10§7个产出线程");
<modularmachinery:dustcollector_factory_controller>.addTooltip("§7注:由于部分特殊原因,其普通控制器无法在JEI里找到,但实际上你仍然可以制造");
<modularmachinery:dustcollector_factory_controller>.addTooltip("§7所以如果你发现你的科技被这台机器卡住,不妨去§aFTB§7任务里寻找一下普通控制器的合成");
addMachineinformation_normal("dustcollector",7,8);
<modularmachinery:dustcollector_controller>.addTooltip("§8掠夺深空资源");
<modularmachinery:dustcollector_controller>.addTooltip("§7中子素吸积盘的替代品,可以产出中子素系列所有物品");
<modularmachinery:dustcollector_controller>.addTooltip("§7同时也产出部分尘埃物质");
addMachineinformation_fact("dimensionreaper",11,5,false);
<modularmachinery:dimensionreaper_factory_controller>.addTooltip("§b由此,迈入时空的永恒求索");
<modularmachinery:dimensionreaper_factory_controller>.addTooltip("§7具体机制与使用教程请查看§9研究终端");
<modularmachinery:dimensionreaper_factory_controller>.addTooltip("§7当进行了一次正常运行时,其产出的倍率=§a一次运行中执行核心配方总数§7+§e结算产出乘数");
<modularmachinery:dimensionreaper_factory_controller>.addTooltip("§9我们从未真正理解它,直到我们亲手打碎了它");
addMachineinformation_fact("spacetime_gestalt",12,1,false);
<modularmachinery:spacetime_gestalt_factory_controller>.addTooltip("§9启动大规模的智慧元件产线");
<modularmachinery:spacetime_gestalt_factory_controller>.addTooltip("§7快速制造多边矩阵液态金属阵列,§4纳米蜂群,§8粗制磁共振电路§7等大量工业原料");
addMachineinformation_fact("groundzero",16,1,false);
<modularmachinery:groundzero_factory_controller>.addTooltip("§5跨越维度的追猎");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7由于§c虹§e彩§9行§a星§7等特殊行星在不可见维度上的非线性移动");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7将采集工作站长期部署在其表面非常不现实");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7但每颗特殊行星造成的§9维度弯曲区域§7十分有限");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7实际上我们可以通过§b持续的观测§7确定其在不可见维度移动后§b相对长期滞留的空间位置");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7在相应的空间位置建立多个§9引力干涉阵列§7,在有限的时间内尽可能的§a遏制其移动");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7便可以最大化利用§c行星资源");
<modularmachinery:groundzero_factory_controller>.addTooltip("§e具体机制如下:");
<modularmachinery:groundzero_factory_controller>.addTooltip("§c正式启动前需要锁定一颗行星!");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7当成功锁定一颗行星后,将会进行一轮初始观测,随机生成§a10-15§7个相应的可能落点");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7其中存在§b4-5§7个引力异常点");
<modularmachinery:groundzero_factory_controller>.addTooltip("§5环星阵列§7拥有两种工作模式");
<modularmachinery:groundzero_factory_controller>.addTooltip("§71.§6观测模式:");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7可以执行以下两种操作");
<modularmachinery:groundzero_factory_controller>.addTooltip("§71.可以执行§a观测配方§7,持续对锁定的行星进行§b落点观测§7并§e记录出现次数");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7每执行完一次观测,异常行星则会§b移动至下一个可能落点");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7有§a40%§7概率落在普通落点,§7有§b60%§7概率落在§9引力异常点");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7每执行§a20§7次观测,则可根据当前样本拟合出相关的运动方程,使得所有§9引力异常点§7的记录出现次数§a+1");
<modularmachinery:groundzero_factory_controller>.addTooltip("§72.选择相应的可能落点,建立§9引力干涉控制阵列");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7每次选择一个新的可能落点建立控制阵列,所需要的阵列耗材为:2^§a(已经建立控制阵列的点)");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7但如果所有§9引力异常点§7上都§a已经建立了控制阵列§7,则后续建立阵列的材料消耗倍率§e固定为1.0");
<modularmachinery:groundzero_factory_controller>.addTooltip("§c采集模式:");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7启动采集后,行星则会根据§6观测模式§7中描述的运动规律进行持续运动");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7当且仅当特殊行星§c移动至§7已经建立§a控制阵列§7的落点上时,§7才可以获取相应产物");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7其产出倍率为:1.0*§a(已经建立控制阵列的点)");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7简而言之,你需要做的:");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7使用§a观测配方§7确定哪些点是§9引力异常点");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7尽快锁定所有§9引力异常点§7使得§e建立阵列§7的代价最小");
<modularmachinery:groundzero_factory_controller>.addTooltip("§7以最小的代价在所有可能落点上§a建立控制阵列");
addMachineinformation_fact("irisx_00147",11,0,false);
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§4永无止境的灼烧");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§7拥有三个控制器,§4工程核心§7,§c合金铸造核心§7,§c高温铸造核心");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§4工程核心:§7执行终末工程特有的§9特殊合金§7配方");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§c合金铸造核心:§7执行§2合金炉§7的煅烧配方");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§c高温铸造核心:§7执行§e高温合金熔铸枢纽§7的煅烧配方");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§7拥有§615§7个熔铸线程,初始所有线程的并行均为§4512");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§7可通过§c堆芯升级§7提升并行上限,最高可达§420亿");
<modularmachinery:irisx_00147_factory_controller>.addTooltip("§c其余两个子模块的并行也由主控制器的并行上限决定");
addMachineinformation_fact("laseraccelerator",10,8,false);
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§b使用特殊技术的紧凑型加速器");
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§7初始使用时需要进行§a充能§7,当§e能量达到上限§7时可以启动相关配方");
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§7在运行过程中§2无法输入能量§7,其§9并行上限§7会随着能量存储的减少而逐渐提高");
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§7使用不同的能量立方可以提升§9充能上限§7与§b充能速度");
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§c能量立方Mk1:§9100K§7,§b500.0K RF/tick");
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§6能量立方Mk2:§91M§7,§b10M.0K RF/tick");
<modularmachinery:laseraccelerator_factory_controller>.addTooltip("§9能量立方Mk3:§92M§7,§b20M.0K RF/tick");
addMachineinformation_fact("lhcparticle",11,0,false);
<modularmachinery:lhcparticle_factory_controller>.addTooltip("§9重现创世的一瞬");
<modularmachinery:lhcparticle_factory_controller>.addTooltip("§7具体机制与使用教程请查看§9研究终端§7与§2JEI配方");
<modularmachinery:lhcparticle_factory_controller>.addTooltip("§7拥有一个升级组件");
<modularmachinery:lhcparticle_factory_controller>.addTooltip("§9封闭类时曲线§1计算§b系统阵列:§7开放额外的输出端口,与§bATLAS-CMS§7监测器同时可以运行");
<modularmachinery:lhcparticle_factory_controller>.addTooltip("§7额外提供§b500mb/tick§7的§9异常希格斯介质§7输出");
addMachineinformation_fact("lightpressurelaunchunit",10,2,false);
<modularmachinery:lightpressurelaunchunit_factory_controller>.addTooltip("§e飞行的西西弗斯");
<modularmachinery:lightpressurelaunchunit_factory_controller>.addTooltip("§7搭载§e光驱单元§7,尝试抵近§8时空裂隙");
<modularmachinery:lightpressurelaunchunit_factory_controller>.addTooltip("§7由于§8时空裂隙§7的特殊性,所以采用§b光子轰击§7驱动来最大程度的靠近它");
<modularmachinery:lightpressurelaunchunit_factory_controller>.addTooltip("§7具体机制与使用教程请查看§2JEI配方");
<modularmachinery:lightpressurelaunchunit_factory_controller>.addTooltip("§7一旦§b光子§7供给量不足,§e光驱单元§7将会立即§c返航§7并结算");
<modularmachinery:lightpressurelaunchunit_factory_controller>.addTooltip("§7所以想让光驱单元返航,断掉光子供给即可");
addMachineinformation_fact("loftstormsite",10,3,false);
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§6架起天空之桥");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§7发射四种航天器用于提升§b近地轨道§a通信中枢§7中的§e阵列等级");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§7每§b200§7点航天器点数可以将阵列等级提升§a1§7级");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§7不同航天器与阵列等级对应关系如下");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§b遥感卫星§7->§b维护阵列");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§c射电望远镜组件阵列§7->§c观测阵列");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§a运载火箭§7->§a运载阵列");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§6采集无人机§7->§6采集阵列");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§7将绑定了§a近地通信中枢控制器§7的§b模式定位坐标卡§7提供给基座即可建立与中枢的联系");
<modularmachinery:loftstormsite_factory_controller>.addTooltip("§7注:基座必须在绑定§b近地轨道§a通信中枢§7且§9近地通信中枢§7已被发射,§b信息管理中枢§7线程运行时才可正常运作");
addMachineinformation_fact("massanomaldevice",10,5,false);
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§9操纵质量");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§7极其强大的矿物处理,分为两种运行模式,产出分别可达§a固定x32§7和§e最高x512");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§9拥有两种运行模式");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§7模式1:§e稳态希格斯场:§7输入§5紫晶素§7和§6硫酸§7,可处理§a20亿§7上限的矿物");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§7无需任何额外操作,固定§ax32§7倍产出矿物并§9优先结算奇点");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§7模式2:§b干涉希格斯场:§7输入§9异常希格斯介质§7和时空束流,进行额外操作,可处理§a20亿§7上限的矿物");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§7具体机制与使用教程请查看§2JEI配方");
<modularmachinery:massanomaldevice_factory_controller>.addTooltip("§7最高可达§ex512§7倍产出矿物并§9优先结算奇点");
addMachineinformation_fact("orionengine",10,8,false);
<modularmachinery:orionengine_factory_controller>.addTooltip("§c全功率启动!");
<modularmachinery:orionengine_factory_controller>.addTooltip("§7可以燃烧绝大部分燃料,产出§6燃料基质§7与相当可观的发电");
<modularmachinery:orionengine_factory_controller>.addTooltip("§7每个燃料都有自己的§9独立线程§7与§a并行上限");
<modularmachinery:orionengine_factory_controller>.addTooltip("§7所以灌入你的所有燃料即可");
<modularmachinery:orionengine_factory_controller>.addTooltip("§7除此之外,也可以使用原始的§d等离子体§7与§5液态D-T燃料§7作为燃料");
addMachineinformation_fact("planetobserver",8,7,false);
<modularmachinery:planetobserver_factory_controller>.addTooltip("§e去遍历未见,去记录未知");
<modularmachinery:planetobserver_factory_controller>.addTooltip("§7接收模糊天体数据模型并进行分析");
<modularmachinery:planetobserver_factory_controller>.addTooltip("§7产出不同的§9行星坐标");
<modularmachinery:planetobserver_factory_controller>.addTooltip("§7当遥感卫星点数大于§a200§7时,才可以正常进行观测");
<modularmachinery:planetobserver_factory_controller>.addTooltip("§7当遥感卫星点数大于§a200§7时,此后每提供§a200§7点数,观测配方的时间就减少§920%");
<modularmachinery:planetobserver_factory_controller>.addTooltip("§7点数上限为§61000");
addMachineinformation_fact("precisecomplex",7,0,false);
<modularmachinery:precisecomplex_factory_controller>.addTooltip("§b集成高科工作站");
<modularmachinery:precisecomplex_factory_controller>.addTooltip("§7集成§a机械核心装配机§7,§b精密装配机§7的所有配方");
<modularmachinery:precisecomplex_factory_controller>.addTooltip("§7拥有§610§7个独立线程,每个线程§a4096§7并行");
<modularmachinery:precisecomplex_factory_controller>.addTooltip("§6觉醒龙素等离子喷口§7和§8混沌龙素谐振管§7均可正常安装");
addMachineinformation_fact("prometheus",10,6,false);
<modularmachinery:prometheus_factory_controller>.addTooltip("§9深入量子领域");
<modularmachinery:prometheus_factory_controller>.addTooltip("§7可以快速合成§a盈能水晶§7,§5UU水晶§7,§b魔力水晶§7,§6盈能地心石英水晶");
<modularmachinery:prometheus_factory_controller>.addTooltip("§7可衰退§9下一阶段§7的特殊流体,产出§b前一阶段§7的特殊流体");
addMachineinformation_fact("simulateneutronstarpointx",13,9,false);
<modularmachinery:simulateneutronstarpointx_factory_controller>.addTooltip("§9极端强大的引力吞噬着周围一切的游离物质,甚至撕碎天体本身");
<modularmachinery:simulateneutronstarpointx_factory_controller>.addTooltip("§8尘埃物质§9吸积盘§4PROMAX版");
<modularmachinery:simulateneutronstarpointx_factory_controller>.addTooltip("§7产出巨量§8中子素系列§7,游离物质,§9零度行星流体§7与§8时空束流");
<modularmachinery:simulateneutronstarpointx_factory_controller>.addTooltip("§7拥有§632§7个独立线程");
<modularmachinery:simulateneutronstarpointx_factory_controller>.addTooltip("§7现在可以退役你的光帆了(笑)");
addMachineinformation_fact("solarwindcollector",6,8,false);
<modularmachinery:solarwindcollector_factory_controller>.addTooltip("§e拦下太阳的怒吼");
<modularmachinery:solarwindcollector_factory_controller>.addTooltip("§7产出数量可观的§e氦-3§7和§b星能聚集光子");
<modularmachinery:solarwindcollector_factory_controller>.addTooltip("§7拥有§68§7个独立线程");
addMachineinformation_fact("spacestation_ii",11,0,false);
addMachineinformation_fact("starcomputer",11,2,false);
addMachineinformation_fact("acdcenter",11,2,false);
addMachineinformation_fact("starcontrolx",9,9,false);
<modularmachinery:starcontrolx_factory_controller>.addTooltip("§c尝试制造一颗太阳");
<modularmachinery:starcontrolx_factory_controller>.addTooltip("§7以不可思议的速度制造熔融物质");
<modularmachinery:starcontrolx_factory_controller>.addTooltip("§7实际熔化物质的时间低于§c1tick");
<modularmachinery:starcontrolx_factory_controller>.addTooltip("§7拥有§632§7个独立线程,每个线程拥有§a65536§7并行");
addMachineinformation_fact("vaticlaser",11,4,false);
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§9下一世代的液体处理设施");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§7拥有三种成型结构:§9超低温逆熵运行核心§7,§b超能魔力聚合核心§7,§d多模态液体自增殖核心");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§9超低温逆熵运行核心§7成型条件:§7需要§9蓝色染色玻璃§7和§9超冷原子机械方块");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§7制造大量§9必需§7的工业流体");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§b超能魔力聚合核心§7成型条件:§7需要§3青色染色玻璃§7和§b魔力聚合机械方块");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§7产出§b液态魔力");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§d多模态液体自增殖核心§7成型条件:§7需要§5紫色染色玻璃§7和§5多模态物质机械方块");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§7产出§5紫晶素");
<modularmachinery:vaticlaser_factory_controller>.addTooltip("§7每个核心拥有§62§7个独立线程");
addMachineinformation_fact("basic_zeropressure",11,7,false);
<modularmachinery:basic_zeropressure_factory_controller>.addTooltip("§b静止之海");
<modularmachinery:basic_zeropressure_factory_controller>.addTooltip("§7集成§6原子重构机§7的所有配方并减少§690%§7的配方时间");
<modularmachinery:basic_zeropressure_factory_controller>.addTooltip("§7存在大量独占配方");
<modularmachinery:basic_zeropressure_factory_controller>.addTooltip("§7可以制造§7局部§9静滞点§b时空重塑§9发生器§7用于加速模块化机器");
<modularmachinery:basic_zeropressure_factory_controller>.addTooltip("§7拥有§614§7个独立线程,未标注并行的配方拥有§a128§7并行");
addMachineinformation_fact("stargate_centralx",17,0,false);
addMachineinformation_fact("mega_windturbine",12,1,false);
addMachineinformation_normal("mega_windturbine",11,1);
addMachineinformation_fact("mega_industrialcrusher",15,1,false);
addMachineinformation_fact("mega_magicalcrafttable",15,1,false);
addMachineinformation_fact("mega_compressor",15,1,false);
addMachineinformation_fact("mega_injectiondevice",15,1,false);
addMachineinformation_fact("mega_shroudneedle",17,1,false);
addMachineinformation_fact("mega_psionicsiphonmatrix",17,1,false);
addMachineinformation_fact("giga_arcanceassemblyline",17,1,false);
addMachineinformation_fact("giga_dimensionallyfocusengravingarray",17,1,false);
addMachineinformation_fact("giga_cosmiccasket",18,1,false);
addMachineinformation_fact("giga_dimensionallytranscendentplasmaforge",18,1,false);
addMachineinformation_fact("giga_timespacesingularity",18,1,false);
addMachineinformation_fact("giga_transdimensionalassemblyline",18,1,false);
addMachineinformation_fact("spacestation_iii",18,1,false);
addMachineinformation_normal("giga_singularitycore",17,0);
addMachineinformation_normal("giga_blackholecore",17,0);
addMachineinformation_fact("giga_negativephasecollector",19,1,false);
addMachineinformation_fact("zeromatrix",15,0,false);
<modularmachinery:zeromatrix_factory_controller>.addTooltip("§b汲取无尽的零点能");
<modularmachinery:zeromatrix_factory_controller>.addTooltip("§9拥有两种运行模式");
<modularmachinery:zeromatrix_factory_controller>.addTooltip("§7模式1:§6施温格效应电场:§7无条件§a40T/tick§7发电并产出“虚空”与反物质");
<modularmachinery:zeromatrix_factory_controller>.addTooltip("§6在此模式下装载§7恒星级§1超§9时§b空§e核心反应矩阵§7并输入§c约束热域行星§7可将发电提升至§a200T/tick§7并§ax2倍§7物质产出");
<modularmachinery:zeromatrix_factory_controller>.addTooltip("§7模式2:§9局部亚稳态真空场衰退:§7此模式下需要每tick输入§9100mb§b异常希格斯介质,§7发电量达§a2P/tick§7并§ax4倍§7物质产出");
<modularmachinery:zeromatrix_factory_controller>.addTooltip("§6此模式需要装载§7恒星级§1超§9时§b空§e核心反应矩阵");
addMachineinformation_fact("dimensioncarver",18,1,false);
addMachineinformation_fact("collapse_generator",11,2,false);
<modularmachinery:collapse_generator_factory_controller>.addTooltip("§9天幕引擎§7的一种替代方案");
<modularmachinery:collapse_generator_factory_controller>.addTooltip("§7使用更加安全和温和的手段产出§8暗物质");
<modularmachinery:collapse_generator_factory_controller>.addTooltip("§7同时也可以产出少量§9天幕引擎§7的§5特殊流体");
addMachineinformation_fact("mega_spaceelevator",16,0,false);
addMachineinformation_fact("test_irisx",10,0,false);
<modularmachinery:test_irisx_factory_controller>.addTooltip("§b工业性能优良的新型魔力聚合设备");
<modularmachinery:test_irisx_factory_controller>.addTooltip("§4IRISX项目§7的另一分支");
<modularmachinery:test_irisx_factory_controller>.addTooltip("§7拥有§610§7个独立线程,每个线程拥有§a65536§7并行");
addMachineinformation_fact("asteroidbcs",10,0,false);
<modularmachinery:asteroidbcs_factory_controller>.addTooltip("§9部署在行星上的量产型采集设备");
<modularmachinery:asteroidbcs_factory_controller>.addTooltip("§7通过航天器构建的运输系统获取行星物质");
<modularmachinery:asteroidbcs_factory_controller>.addTooltip("§7由于技术限制,无法长期部署在§e闪耀行星§7,§d山铜行星§7,§c虹§e彩§9行§a星§7上");
addMachineinformation_fact("licsac",10,2,false);
<modularmachinery:licsac_factory_controller>.addTooltip("§e高精尖运算元件装配中心");
<modularmachinery:licsac_factory_controller>.addTooltip("§7采用新型材料加工技术,§a低成本且快速§7的产出算力元件和电子元件");
<modularmachinery:licsac_factory_controller>.addTooltip("§7拥有§620§7个独立线程");
addMachineinformation_fact("warmatrix",10,5,false);
<modularmachinery:warmatrix_factory_controller>.addTooltip("§4虚拟中演绎文明的轮回");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§7拥有以下三个功能:");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§71.§7快速将§8缺陷§7模型提升至§6自我意识§7等级");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§72.§7通过导入的数据模型快速产出§a原始物质");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§73.通过§b集成§a智慧核心§7高效率产出§c怪物素材");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§7不同模型在系统中划分为§a4§7种不同的文明集群:§b主世界§7,§c下界§7,§d末地§7,§6传奇生物");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§7导入不同文明集群所属的怪物模型将影响对应集群的§a物质产出");
<modularmachinery:warmatrix_factory_controller>.addTooltip("§7具体计算公式请查看配方§2JEI");
addMachineinformation_fact("lifemanipulator",10,6,false);
<modularmachinery:lifemanipulator_factory_controller>.addTooltip("§4解构生命本身,操纵生命力量");
<modularmachinery:lifemanipulator_factory_controller>.addTooltip("§7需要§4创造匕首§7启动");
<modularmachinery:lifemanipulator_factory_controller>.addTooltip("§7利用创造匕首的力量产出§c生物灵魂§7和§4生命源质");
<modularmachinery:lifemanipulator_factory_controller>.addTooltip("§7快速执行血之祭坛的常用配方");
<modularmachinery:lifemanipulator_factory_controller>.addTooltip("§7每个配方都拥有§6独立的线程§7,每个线程拥有§a4096§7并行");
addMachineinformation_fact("zerogravity_fieldguidereactor",7,0,false);
<modularmachinery:zerogravity_fieldguidereactor_factory_controller>.addTooltip("§9创造理想条件下的高效固液反应");
<modularmachinery:zerogravity_fieldguidereactor_factory_controller>.addTooltip("§7集成§9共价超载器§7,§5Fluix晶胞催化铸造工厂§7的所有配方并减少§699%§7的配方时间");
<modularmachinery:zerogravity_fieldguidereactor_factory_controller>.addTooltip("§7拥有§614§7个独立线程§7,每个线程拥有§a4096§7并行");
addMachineinformation_fact("mega_neutronactivator",11,8,false);
addMachineinformation_fact("huge_disscociation_device",8,6,false);
addMachineinformation_fact("tree_diagram_computer_x",15,0,false);
addMachineinformation_fact("nexus_ich",15,0,false);
addMachineinformation_fact("m2scn",10,0,false);
<modularmachinery:m2scn_factory_controller>.addTooltip("§7尝试制造一颗§9可控§7的§0黑洞");
<modularmachinery:m2scn_factory_controller>.addTooltip("§7通过§5紫晶素§7和§9奇点§7制造一颗超小型质量奇点");
<modularmachinery:m2scn_factory_controller>.addTooltip("§7利用§a矿物数据模型§7影响蒸发出的物质,§7诱导聚合§c永恒奇点");
<modularmachinery:m2scn_factory_controller>.addTooltip("§7具体机制与产出计算请查看配方§2JEI");
addMachineinformation_fact("helios",10,2,false);
addMachineinformation_fact("east_tokamak",10,5,false);
<modularmachinery:east_tokamak_factory_controller>.addTooltip("§c东方超环");
<modularmachinery:east_tokamak_factory_controller>.addTooltip("§cEAST§7是中国科学院等离子体所自主设计,研制并拥有完全知识产权的磁约束核聚变实验装置");
<modularmachinery:east_tokamak_factory_controller>.addTooltip("§7是世界上第一个非圆截面全超导托卡马,也是首个实现稳态高约束模式运行且持续时间达到百秒量级的托卡马克核聚变实验装置");
<modularmachinery:east_tokamak_factory_controller>.addTooltip("§7它的功能很简单,将圆石烧制为§d等离子体");
<modularmachinery:east_tokamak_factory_controller>.addTooltip("§cPOWER!");
addMachineinformation_fact("advanced_field_facility",9,6,false);
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§9力场操纵合成加工复合体");
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§7极高效率的材料加工中心");
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§7力场控制矩阵的§9等级§7影响着并行与加工效率");
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§7等级识别依次为:§b水晶§7,中子,§d落星§7,§c寰宇§7,§9方舟§7,§4余烬-§7虚空");
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§7力场控制矩阵每提升§a1§7级,§7并行上限§6x2");
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§7当等级为§c寰宇§7及其以上,配方耗时再减少§699%");
<modularmachinery:advanced_field_facility_factory_controller>.addTooltip("§7拥有§610§7个独立线程,§7每个线程的初始并行为§a16384");
addMachineinformation_fact("wizard_drill",6,2,false);
<modularmachinery:wizard_drill_factory_controller>.addTooltip("§d魔法的尽头是科技");
<modularmachinery:wizard_drill_factory_controller>.addTooltip("§7输入§b液态魔力§7产出§5巫术学水晶");
<modularmachinery:wizard_drill_factory_controller>.addTooltip("§7原版的§a矿机升级部件§7可作为§b催化剂§7提升产出");
addMachineinformation_fact("high_density_energy_focus_core",9,1,false);
<modularmachinery:high_density_energy_focus_core_factory_controller>.addTooltip("§7并行上限为§a25600");
addMachineinformation_fact("mega_advancedwarmatrix",15,0,false);
addMachineinformation_fact("mega_neutronactivator",11,8,false);
addMachineinformation_fact("huge_mixer",5,2,false);
<modularmachinery:huge_mixer_factory_controller>.addTooltip("§2Look Familiar?");
addMachineinformation_fact("giga_qft",16,0,false);
addMachineinformation_fact("giga_iridiosamariumchipforge",18,0,false);
addMachineinformation_fact("mega_spaceelevatorminemodule",16,0,false);
addMachineinformation_fact("crafting_adv1",3,0,false);
addMachineinformation_fact("crafting_eli2",4,0,false);
addMachineinformation_fact("crafting_ult3",5,0,false);
addMachineinformation_fact("irisx_00147_mode2",11,0,false);
<modularmachinery:irisx_00147_mode2_factory_controller>.addTooltip("§4余烬工程核心的子模块");
<modularmachinery:irisx_00147_mode2_factory_controller>.addTooltip("§7执行§e高温合金熔铸枢纽§7的配方");
<modularmachinery:irisx_00147_mode2_factory_controller>.addTooltip("§c其并行由工程核心的并行上限决定");
addMachineinformation_fact("irisx_00147_mode1",11,0,false);
<modularmachinery:irisx_00147_mode1_factory_controller>.addTooltip("§4余烬工程核心的子模块");
<modularmachinery:irisx_00147_mode1_factory_controller>.addTooltip("§7执行§2合金炉§7的配方");
<modularmachinery:irisx_00147_mode1_factory_controller>.addTooltip("§c其并行由工程核心的并行上限决定");
addMachineinformation_fact("ssps",8,5,false);
<modularmachinery:ssps_factory_controller>.addTooltip("§b效法羲和驭天马,志在长空牧群星");
<modularmachinery:ssps_factory_controller>.addTooltip("§7通过§9同步轨道§e太阳能§b空间站§7上搭载的太阳能模块");
<modularmachinery:ssps_factory_controller>.addTooltip("§7将太阳能转化为微波发送至地面接收基站");
<modularmachinery:ssps_factory_controller>.addTooltip("§b太阳能板等级§7每提升§a1§7级,能量产出§ax2§7,§7物质产出§b加倍");
addMachineinformation_fact("ssps_universesite",8,9,false);
<modularmachinery:ssps_universesite_factory_controller>.addTooltip("§9更靠近太阳一些");
<modularmachinery:ssps_universesite_factory_controller>.addTooltip("§c在空间站维度§7制造§b逐日工程同步终端");
<modularmachinery:ssps_universesite_factory_controller>.addTooltip("§b不同等级§7的太阳能板制造出的同步终端将影响接收基站的§a最终产出");
addMachineinformation_fact("speedlightsite",15,0,false);
addMachineinformation_fact("giga_condenseddarkplasmaturbine",18,0,false);
addMachineinformation_fact("astral_combine_device",7,6,false);
addMachineinformation_fact("nast",5,6,false);
addMachineinformation_fact("natus_re001",14,0,false);
addMachineinformation_fact("invasion_device",11,7,false);
addMachineinformation_fact("omhd",13,4,false);
addMachineinformation_fact("star_annihilation_engine",14,5,false);
<modularmachinery:star_annihilation_engine_factory_controller>.addTooltip("§4彻底毁灭一颗行星");
<modularmachinery:star_annihilation_engine_factory_controller>.addTooltip("§7进阶版§c热域行星反应堆§7,最大钻探深度为§7:§412000KM");
<modularmachinery:star_annihilation_engine_factory_controller>.addTooltip("§7基础发电为§c100T/TICK§7,§7每向下钻探§c1000KM§7,发电量提升§41§7倍数,物质产出提升§41§7倍");
<modularmachinery:star_annihilation_engine_factory_controller>.addTooltip("§7最大发电量可达§c1.2P/TICK");
<modularmachinery:star_annihilation_engine_factory_controller>.addTooltip("§c热域行星将彻底解体,所以不会有任何§4“余烬”§c产生");
<modularmachinery:star_annihilation_engine_factory_controller>.addTooltip("§7当反应完毕一颗行星时产出两种§8奇异物质");
addMachineinformation_fact("bio_cube",4,0,false);
addMachineinformation_fact("rawdrill",2,0,false);
addMachineinformation_fact("endtech_earth_drill",5,6,false);
addMachineinformation_fact("tss_site",3,0,false);
addMachineinformation_fact("pelotriodevice",8,0,false);